export const POPULAR_SERVICES: Record<string, string> = {
    // === Global Entertainment & Streaming ===
    "netflix": "https://www.netflix.com/cancelplan",
    "spotify": "https://www.spotify.com/account/overview/",
    "amazon prime": "https://www.amazon.com/mc/optOutEligibility",
    "amazon prime video": "https://www.amazon.com/mc/optOutEligibility",
    "amazon": "https://www.amazon.com/mc/optOutEligibility",
    "apple tv": "https://support.apple.com/en-us/118428",
    "apple tv+": "https://support.apple.com/en-us/118428",
    "apple music": "https://support.apple.com/en-us/118428",
    "apple one": "https://support.apple.com/en-us/118428",
    "disney+": "https://www.disneyplus.com/account/subscription",
    "disney plus": "https://www.disneyplus.com/account/subscription",
    "hbo max": "https://www.max.com/account/subscription-management",
    "max": "https://www.max.com/account/subscription-management",
    "hulu": "https://secure.hulu.com/account/cancel",
    "youtube premium": "https://www.youtube.com/paid_memberships",
    "youtube music": "https://www.youtube.com/paid_memberships",
    "youtube tv": "https://tv.youtube.com/settings/membership",
    "twitch": "https://www.twitch.tv/settings/subscriptions",
    "paramount+": "https://www.paramountplus.com/account/cancel-subscription",
    "paramount plus": "https://www.paramountplus.com/account/cancel-subscription",
    "peacock": "https://www.peacocktv.com/account/plan",
    "crunchyroll": "https://www.crunchyroll.com/acct/membership",

    // === Middle East & North Africa (MENA) Streaming ===
    "shahid": "https://shahid.mbc.net/en/widgets/manage-subscriptions",
    "shahid vip": "https://shahid.mbc.net/en/widgets/manage-subscriptions",
    "watch it": "https://watchit.com/settings/subscription",
    "watchit": "https://watchit.com/settings/subscription",
    "osn": "https://osnplus.com/my-account",
    "osn+": "https://osnplus.com/my-account",
    "osn plus": "https://osnplus.com/my-account",
    "tod": "https://www.tod.tv/en/my-account",
    "tod tv": "https://www.tod.tv/en/my-account",
    "bein connect": "https://connect.bein.com/my-account",
    "starzplay": "https://starzplay.com/settings/subscription",
    "starz play": "https://starzplay.com/settings/subscription",
    "yango play": "https://play.yango.com/support/en/subscription-payments/subscribe/cancellation",
    "yango": "https://play.yango.com/support/en/subscription-payments/subscribe/cancellation",
    "anghami": "https://www.anghami.com/manage-account",
    "anghami plus": "https://www.anghami.com/manage-account",
    "stc tv": "https://app.stctv.com/settings/subscription",
    "jawwy tv": "https://app.stctv.com/settings/subscription", // Jawwy TV rebranded to STC TV
    "viu": "https://www.viu.com/ott/mena/en/my-account",

    // === Software, Cloud & Productivity ===
    "adobe": "https://account.adobe.com/plans",
    "adobe creative cloud": "https://account.adobe.com/plans",
    "microsoft 365": "https://account.microsoft.com/services",
    "microsoft": "https://account.microsoft.com/services",
    "office 365": "https://account.microsoft.com/services",
    "github": "https://github.com/settings/billing",
    "github copilot": "https://github.com/settings/billing",
    "notion": "https://www.notion.so/profile/billing",
    "slack": "https://app.slack.com/plans",
    "zoom": "https://zoom.us/billing",
    "dropbox": "https://www.dropbox.com/account/plan",
    "google one": "https://one.google.com/storage",
    "google workspace": "https://admin.google.com/ac/billing/subscriptions",
    "icloud": "https://support.apple.com/en-us/118428",
    "icloud+": "https://support.apple.com/en-us/118428",
    "chatgpt": "https://help.openai.com/en/articles/7232529",
    "chat gpt": "https://help.openai.com/en/articles/7232529",
    "openai": "https://help.openai.com/en/articles/7232529",
    "claude": "https://support.anthropic.com",
    "canva": "https://www.canva.com/settings/billing-and-plans",
    "figma": "https://help.figma.com/hc/en-us/articles/360040328273",
    "linear": "https://linear.app/settings/billing",
    "vercel": "https://vercel.com/dashboard/billing",
    "aws": "https://aws.amazon.com/premiumsupport/knowledge-center/cancel-subscription",
    "digitalocean": "https://cloud.digitalocean.com/account/billing",
    "heroku": "https://dashboard.heroku.com/account/billing",

    // === Gaming ===
    "gamepass": "https://account.microsoft.com/services",
    "xbox game pass": "https://account.microsoft.com/services",
    "psn": "https://www.playstation.com/en-us/playstation-plus/",
    "playstation plus": "https://www.playstation.com/en-us/playstation-plus/",
    "nintendo switch online": "https://accounts.nintendo.com/profile/edit/",
    "ea play": "https://www.ea.com/ea-play",

    // === Utilities & Security ===
    "nordvpn": "https://my.nordaccount.com/dashboard/nordvpn/",
    "expressvpn": "https://www.expressvpn.com/subscriptions",
    "1password": "https://my.1password.com/profile",
    "lastpass": "https://lastpass.com/my/account.php",
    "nordpass": "https://my.nordaccount.com/dashboard/nordpass/",
    "malwarebytes": "https://my.malwarebytes.com/subscriptions",
    "dashlane": "https://app.dashlane.com/settings/billing",

    // === E-commerce, Platforms & Others ===
    "shopify": "https://help.shopify.com/en/manual/your-account/pause-deactivate-store",
    "wix": "https://support.wix.com/en/article/canceling-your-premium-plan",
    "squarespace": "https://account.squarespace.com/billing",
    "grammarly": "https://account.grammarly.com/subscription",
    "duolingo": "https://support.duolingo.com/hc/en-us/articles/4404745271565",
    "linkedin premium": "https://www.linkedin.com/premium/manage",
    "linkedin": "https://www.linkedin.com/premium/manage",
    "deezer": "https://www.deezer.com/account/subscription",
    "tidal": "https://tidalhifi.com/account",
    "audible": "https://www.audible.com/hz/mycdlibrary/marketplaceCancellation",
    "kindle unlimited": "https://www.amazon.com/kindle-dbs/submanager/manage",
    "jasper": "https://app.jasper.ai/settings/billing",
    "midjourney": "https://www.midjourney.com/account",
    "cursor": "https://www.cursor.com/settings",
};
